stages:
  prepare:
    cmd: uv run src/prepare.py data/CICIDS2017_improved
    deps:
    - data/CICIDS2017_improved/friday.csv
    - data/CICIDS2017_improved/monday.csv
    - data/CICIDS2017_improved/thursday.csv
    - data/CICIDS2017_improved/tuesday.csv
    - data/CICIDS2017_improved/wednesday.csv
    - src/prepare.py
    params:
    - prepare.split
    - prepare.oversampling.method
    - prepare.oversampling.method_params
    outs:
    - data/prepared
    - logs/prepare.log

  train:
    cmd: uv run src/train.py
    deps:
    - data/prepared/train.csv
    - src/train.py
    params:
    - train.classifier
    - train.classifier_params
    outs:
    - data/models/improved_c45_model.joblib
    - logs/train.log

  evaluate:
    cmd: uv run src/evaluate.py
    deps:
    - data/models/improved_c45_model.joblib
    - data/prepared/test.csv
    - src/evaluate.py
    outs:
    - evaluate
    - logs/evaluate.log
metrics:
- evaluate/metrics.json
plots:
- evaluate/plots/images
- evaluate/plots/sklearn/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
artifacts:
  confusion_matrix:
    path: confusion_matrix.txt
    type: "0: [316432      0      0      0      0      0      3      0      1    \
      \  0\n      2      0      0      0      1      2      0     12     10      0\n\
      \      0      0      0      0      0      0]\n1: [  0 150   0   0   0   0  \
      \ 0   0   0   0   0   0   0   0   0   0   0   0\n   0   0   0   0   0   0  \
      \ 0   0]\n2: [  0   0 774   0   0   0   0   0   0   0   0   0   0   0   0  \
      \ 0   0   0\n   0   0   0   0   0   0   0   0]\n3: [    5     0     0 18948\
      \     0     0     0     0     0     0     0     0\n     0     0     0     0\
      \     0     0     0     0     0     0     0     0\n     0     0]\n4: [  11 \
      \   0    0    0 1579    0    1    0    3    0    1    0    0    0\n    0   \
      \ 0    0    0    0    0    0    0    0    0    0    0]\n5: [0 0 0 0 0 9 0 6
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n6: [   10     0     0     0     0    \
      \ 0 31820     0     1     0     4     0\n     0     0     0     0     0    \
      \ 0     0     0     0     0     0     0\n     0     0]\n7: [  0   0   0   0\
      \   0   9   0 105   0   0   0   0   0   0   0   0   0   0\n   0   0   0   0\
      \   0   0   0   0]\n8: [ 49   0   0   0   2   0   0   0 293   0   7   0   0\
      \   0   0   0   0   0\n   0   0   0   0   0   0   0   0]\n9: [  0   0   0  \
      \ 0   0   0   0   0   0 661   0   1   0   0   0   0   0   0\n   0   0   0  \
      \ 0   0   0   0   0]\n10: [ 28   0   0   0   0   0   0   0  10   0 741   0 \
      \  0   0   0   0   0   2\n   0   0   0   0   0   0   0   0]\n11: [  0   0  \
      \ 0   0   0   0   0   1   0   0   0 387   0   0   0   0   0   0\n   0   0  \
      \ 0   0   0   0   0   0]\n12: [  0   0   0   0   0   0   0   0   0   0   0 \
      \  0 751   0   0   0   0   0\n   0   0   0   0   0   0   0   0]\n13: [0 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n14: [1 0 0 0 0 0 0 0 0 0 0 0
      0 0 2 0 0 0 0 0 0 0 0 0 0 0]\n15: [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0
      0 0 0 0 0]\n16: [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 11  0  0  0\
      \  0  0  0  0\n  0  0]\n17: [  117     0     0     0     0     0     1     0\
      \     0     0     0     0\n     0     0     0     0     0 13087  1243     0\
      \     0     0     0     0\n     0     0]\n18: [   12     0     0     0     0\
      \     0     0     0     0     0     0     0\n     0     0     0     0     0\
      \   800 30908     0     0     0     0     0\n     0     0]\n19: [  0   0   0\
      \   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0\n   0 604   0\
      \   0   0   0   0   0]\n20: [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 5 0 0 0
      0 0]\n21: [12  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0\
      \  0  0\n  0  0]\n22: [  0   0   0   0   0   0   0   2   0   0   0   0   0 \
      \  0   0   0   0   0\n   0   0   0   0 230   0   0   2]\n23: [1 0 0 0 1 0 0
      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]\n24: [4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
      0 0 0 0 0 0 0 0 0 0]\n25: [  0   0   0   0   0   0   0   0   0   0   0   0 \
      \  0   0   0   0   0   0\n   0   0   0   1 114   0   0   0]"
