stages:
  prepare:
    cmd: uv run src/prepare.py data/CICIDS2017_improved
    deps:
    - data/CICIDS2017_improved/friday.csv
    - data/CICIDS2017_improved/monday.csv
    - data/CICIDS2017_improved/thursday.csv
    - data/CICIDS2017_improved/tuesday.csv
    - data/CICIDS2017_improved/wednesday.csv
    - src/prepare.py
    params:
    - prepare.split
    - prepare.oversampling.method
    - prepare.oversampling.method_params
    outs:
    - data/prepared
    - logs/prepare.log

  train:
    cmd: uv run src/train.py
    deps:
    - data/prepared/train.csv
    - src/train.py
    params:
    - train.classifier
    - train.classifier_params
    outs:
    - data/models/improved_c45_model.joblib
    - logs/train.log

  evaluate:
    cmd: uv run src/evaluate.py
    deps:
    - data/models/improved_c45_model.joblib
    - data/prepared/test.csv
    - src/evaluate.py
    outs:
    - evaluate
    - logs/evaluate.log
metrics:
- evaluate/metrics.json
plots:
- evaluate/plots/images
- evaluate/plots/sklearn/confusion_matrix.json:
    template: confusion
    x: actual
    y: predicted
    title: Confusion Matrix
    x_label: True Label
    y_label: Predicted Label
